analyzers:
  lidars:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Lidars
    analyzers:
      lidar_front:
        type: diagnostic_aggregator/GenericAnalyzer
        path: lidar_front
        find_and_remove_prefix: 'lidar_center/lidar_center_nodelet_manager_driver: velodyne_packets '
        num_items: 1
        timeout: 2