analyzers:
  lidars:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Lidars
    analyzers:
      lidar_center:
        type: diagnostic_aggregator/GenericAnalyzer
        path: lidar_center
        find_and_remove_prefix: 'lidar_center/os_cloud_node: '
        num_items: 1
        timeout: 2

