image_width: 2064
image_height: 1544
camera_name: camera_fl
distortion_model: plumb_bob
camera_model: plumb_bob
camera_matrix:
  rows: 3
  cols: 3
  data: [3468.73879,             0.,                     1009.90437,
         0.,                     3487.13961,             735.97327,
         0.,                     0.,                     1.]
distortion_coefficients:
  rows: 1
  cols: 5
  data: [ -0.275729, 0.485760, 0.003465, -0.000696, 0.000000 ]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [3394.75537,             0.,                     1008.40783,             0.,
         0.,                     3443.55591,             736.98557,              0.,
         0.,                     0.,                     1.,                     0.]