image_width: 2064
image_height: 1544
camera_name: camera_fr
distortion_model: plumb_bob
camera_model: plumb_bob
camera_matrix:
  rows: 3
  cols: 3
  data: [2319.98737,             0.,                     952.9606,
         0.,                     2330.30968,             754.24939,
         0.,                     0.,                     1.]
distortion_coefficients:
  rows: 1
  cols: 5
  data: [ -0.245184, 0.233866, 0.001396, -0.000115, 0.000000 ]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [2221.71045,             0.,                     947.34993,              0.,
         0.,                     2271.09009,             754.59486,              0.,
         0.,                     0.,                     1.,                     0.]